### ISSUE TITLE
Unable to remove/delete wallet when name is too long

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/multisig.lol#1]
The multisig drop down menu width is static.  When a multisig is created with a longer name it clips off the right edge, which also pushes the remove button out of the visible area.  

![image](https://user-images.githubusercontent.com/12072395/206256822-926ff563-d46a-44d4-b23b-6f5867482d70.png)

Possible fixes would be to update the drop down menu to be larger or more dynamic, or to set a character limit when creating a new multisig.

**Comment by Naim-Bijapure** [comment]
fixed on above pr
